---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: rcon-web-admin
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/fabricesemti80/home-dc-kubernetes.git"
      path: kubernetes/apps/app-cluster/gaming/rcon-web-admin
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 5.0.1
      helm:
        releaseName: rcon-web-admin
        valueFiles:
          - $repo/kubernetes/apps/app-cluster/gaming/rcon-web-admin/values.yaml
  destination:
    name: app-cluster
    namespace: gaming
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
