---
# Doppler Kubernetes Operator Helm values
# https://github.com/DopplerHQ/kubernetes-operator

doppler-kubernetes-operator:
  image:
    repository: mirror.gcr.io/dopplerhq/kubernetes-operator
  resources:
    requests:
      cpu: 50m
      memory: 64Mi
    limits:
      cpu: 250m
      memory: 256Mi
