title: Homepage
description: Homelab dashboard
background: https://source.unsplash.com/2560x1440/?technology,servers,datacenter
headerStyle: clean
hideVersion: true
layout:
  Dashboards:
  Infrastructure:
  Monitoring:
  Productivity:
  Media:
