---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: n8n-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret-apps
    namespace: doppler-operator-system
  project: home-dc-kubernetes
  config: apps
  managedSecret:
    name: n8n-secrets
    namespace: productivity
    type: Opaque
  secrets:
    - N8N_ENCRYPTION_KEY
