---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kestra-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: kestra-secrets
    namespace: productivity
    type: Opaque
  secrets:
    - KESTRA_POSTGRES_PASSWORD
    - KESTRA_DATABASE_URL
    - KESTRA_STORAGE_S3_ACCESS_KEY
    - KESTRA_STORAGE_S3_SECRET_KEY
