---
# Doppler secrets for n8n automation platform
# Declare in Doppler: 
## N8N_BASIC_AUTH_ACTIVE, 
## N8N_BASIC_AUTH_USER, 
## N8N_BASIC_AUTH_PASSWORD, 
## N8N_ENCRYPTION_KEY
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: n8n-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: n8n-secrets
    namespace: automation
    type: Opaque
  secrets:
    - N8N_BASIC_AUTH_ACTIVE
    - N8N_BASIC_AUTH_USER
    - N8N_BASIC_AUTH_PASSWORD
    - N8N_ENCRYPTION_KEY