---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: minecraft-server-pvc
  namespace: gaming
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: cephfs
  resources:
    requests:
      storage: 20Gi
