---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: technitium-rfc2136-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret-infra
    namespace: doppler-operator-system
  project: home-dc-kubernetes
  config: infra
  managedSecret:
    name: technitium-rfc2136-secrets
    namespace: network
    type: Opaque
  secrets:
    - TECHNITIUM_RFC2136_TSIG_KEYNAME
    - TECHNITIUM_RFC2136_TSIG_SECRET
