---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: alertmanager-slack-webhook
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret-apps
    namespace: doppler-operator-system
  project: home-dc-kubernetes
  config: apps
  managedSecret:
    name: alertmanager-slack-webhook
    namespace: monitoring
    type: Opaque
  secrets:
    - SLACK_WEBHOOK_MONITORING
