---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: immich-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret-apps
    namespace: doppler-operator-system
  project: home-dc-kubernetes
  config: apps
  managedSecret:
    name: immich-secrets
    namespace: media
    type: Opaque
  secrets:
    - IMMICH_DB_PASSWORD
