---
fullnameOverride: litellm-postgres
useDeployment: true
nodeSelector:
  kubernetes.io/hostname: infra-cp-01
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
affinity: {}
settings:
  existingSecret: litellm-postgres
  superuser:
    secretKey: LITELLM_POSTGRES_USER
  superuserPassword:
    secretKey: LITELLM_POSTGRES_PASSWORD
userDatabase:
  existingSecret: litellm-postgres
  name:
    secretKey: LITELLM_POSTGRES_DB
  user:
    secretKey: LITELLM_USERDB_USER
  password:
    secretKey: LITELLM_USERDB_PASSWORD
resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 1Gi
storage:
  className: local-path
  requestedSize: 10Gi
  accessModes:
    - ReadWriteOnce
  keepPvc: true
