name: homelab

include:
  - ./traefik/compose.yml
  - ./cloudflared/compose.yml
  - ./arcane/compose.yml
  - ./beszel/compose.yml
  - ./uptime-kuma/compose.yml
  - ./whoami/compose.yml
  - ./bambuddy/compose.yml
  - ./portainer/compose.yml

networks:
  proxy:
    name: homelab_proxy
