---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kestra-basic-auth
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: kestra-basic-auth
    namespace: kestra
    type: Opaque
  secrets:
    - KESTRA_BASIC_AUTH_USERNAME
    - KESTRA_BASIC_AUTH_PASSWORD
