---
apiVersion: v1
kind: Service
metadata:
  name: versitygw
  namespace: kestra
spec:
  selector:
    app.kubernetes.io/name: versitygw
  ports:
    - name: http
      port: 7070
      targetPort: 7070
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: versitygw
  namespace: kestra
spec:
  serviceName: versitygw
  replicas: 1
  selector:
    matchLabels:
      app.kubernetes.io/name: versitygw
  template:
    metadata:
      labels:
        app.kubernetes.io/name: versitygw
    spec:
      nodeSelector:
        kubernetes.io/hostname: infra-cp-01
      tolerations:
        - key: node-role.kubernetes.io/control-plane
          operator: Exists
          effect: NoSchedule
      containers:
        - name: versitygw
          image: versity/versitygw:v1.7.0
          args:
            - --port
            - 0.0.0.0:7070
            - --health
            - /health
            - posix
            - /data
          envFrom:
            - secretRef:
                name: versitygw-root
          env:
            - name: VGW_REGION
              value: eu-west-1
          ports:
            - name: http
              containerPort: 7070
          volumeMounts:
            - name: data
              mountPath: /data
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes:
          - ReadWriteOnce
        storageClassName: local-path
        resources:
          requests:
            storage: 20Gi
