- Infra Cluster - monitoring:
    - Pulse:
        icon: mdi-heart-pulse
        href: https://pulse.krapulax.dev
        description: Infrastructure monitoring
    - Uptime Kuma:
        icon: mdi-monitor-eye
        href: https://uptime.krapulax.dev
        description: External availability monitoring

- Infra Cluster - network:
    - Technitium:
        icon: mdi-dns
        href: https://dns.krapulax.dev
        description: Authoritative local DNS
