---
global:
  createDefaultServiceAccount: false

defaultPodOptions:
  automountServiceAccountToken: false
  annotations:
    reloader.stakater.com/auto: "true"

controllers:
  sterling-pdf:
    replicas: 1
    strategy: RollingUpdate
    containers:
      app:
        image:
          repository: docker.io/stirlingtools/stirling-pdf
          tag: 2.14.2
        env:
          TZ: Europe/London
          DOCKER_ENABLE_SECURITY: "false"
          INSTALL_BOOK_AND_ADVANCED_HTML_OPS: "false"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/info/status
                port: &port 8080
              initialDelaySeconds: 30
              periodSeconds: 15
              timeoutSeconds: 5
              failureThreshold: 4
          readiness: *probes
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /api/v1/info/status
                port: *port
              initialDelaySeconds: 5
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          capabilities: { drop: ["ALL"] }
        resources:
          requests:
            cpu: 250m
            memory: 512Mi
          limits:
            memory: 2Gi

service:
  app:
    controller: sterling-pdf
    ports:
      http:
        port: 80
        targetPort: *port

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: cephfs
    size: 2Gi
    advancedMounts:
      sterling-pdf:
        app:
          - path: /configs
  custom-files:
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: cephfs
    size: 1Gi
    advancedMounts:
      sterling-pdf:
        app:
          - path: /customFiles
  logs:
    type: emptyDir
    globalMounts:
      - path: /logs
