---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: arc-github-app-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: arc-github-app-secret
    namespace: arc-system
    type: Opaque
  secrets:
    - GITHUB_APP_ID
    - GITHUB_APP_INSTALLATION_ID
    - GITHUB_APP_PRIVATE_KEY
  processors:
    GITHUB_APP_ID:
      asName: github_app_id
    GITHUB_APP_INSTALLATION_ID:
      asName: github_app_installation_id
    GITHUB_APP_PRIVATE_KEY:
      asName: github_app_private_key
