---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: arc-github-app-secret
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: arc-github-app-secret
    namespace: arc-system
    type: Opaque
  secrets:
    - github_app_id
    - github_app_installation_id
    - github_app_private_key
