---
replicaCount: 1

image:
  repository: docker.io/itzg/rcon
  tag: "0.14.1-1"
  pullPolicy: IfNotPresent

podAnnotations:
  reloader.stakater.com/auto: "true"

service:
  type: ClusterIP
  httpPort: 80
  wsPort: 4327

ingress:
  enabled: false

resources:
  requests:
    cpu: 50m
    memory: 128Mi
  limits:
    cpu: 500m
    memory: 512Mi

persistence:
  enabled: true
  accessModes: ReadWriteMany
  size: 1Gi
  storageClass: cephfs

rconWeb:
  isAdmin: true
  username: admin
  passwordExistingSecret: rcon-web-admin-secrets
  passwordKey: RCON_WEB_ADMIN_PASSWORD
  game: minecraft
  serverName: Minecraft
  rconHost: minecraft-rcon.gaming.svc.cluster.local
  rconPort: 25575
  rconPasswordExistingSecret: rcon-web-admin-secrets
  rconPasswordKey: RCON_PASSWORD
  websocketRcon: false
  websocketUrl: ws://minecraft-admin-ws.krapulax.dev
  websocketUrlSsl: wss://minecraft-admin-ws.krapulax.dev
