---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: linkwarden-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: linkwarden-secrets
    namespace: productivity
    type: Opaque
  secrets:
    - DATABASE_URL
    - NEXTAUTH_URL
    - NEXTAUTH_SECRET
    - LINKWARDEN_DB_PASSWORD
