---
global:
  createDefaultServiceAccount: false

defaultPodOptions:
  automountServiceAccountToken: false
  securityContext:
    runAsNonRoot: true
    runAsUser: 1000
    runAsGroup: 1000
    fsGroup: 1000
    seccompProfile:
      type: RuntimeDefault

controllers:
  rcon-web-admin:
    replicas: 1
    strategy: Recreate
    annotations:
      secret.reloader.stakater.com/reload: rcon-web-admin-secrets
    containers:
      app:
        image:
          repository: ghcr.io/tekikaito/mc-admin
          tag: "v1.3.3@sha256:8c189639d0bdc91b50e4ffc76d7ddaf136a801cf0d113c6b0b662e1e464e6476"
          pullPolicy: IfNotPresent
        env:
          RCON_HOST: minecraft-rcon.gaming.svc.cluster.local
          RCON_PORT: "25575"
          RCON_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: rcon-web-admin-secrets
                key: RCON_PASSWORD
          SERVER_HOST: minecraft.krapulax.home
          GAME_PORT: "25565"
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8080
              periodSeconds: 10
              timeoutSeconds: 3
              failureThreshold: 3
          readiness: *probes
          startup:
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: 8080
              periodSeconds: 5
              failureThreshold: 30
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          capabilities:
            drop: [ALL]
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

service:
  app:
    controller: rcon-web-admin
    ports:
      http:
        port: 80
        targetPort: 8080
