apiVersion: v1
kind: Secret
metadata:
  name: doppler-token-secret-apps
  namespace: doppler-operator-system
type: Opaque
stringData:
  serviceToken: ENC[AES256_GCM,data:RLaK1HV5Izl2QM/GjuoaKqBVTCpMagNEhWw5bIcFJ29aHSFSLkAAaYEZ0SRzxNyrqCeL00uz,iv:mZrBi4PjB371jwRwMiTLMTepnFgXRNSh4Ua9qgfj2Xc=,tag:Z6IxYM3kemoxIOERDOw/1g==,type:str]
sops:
  age:
    - enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZZExEVlpEWU1mRUVKN3l2
        Uy9zVFZIYWo5N2V1NFpTRU9NWjZ1NC9iUTJzCjlUZDJTSjZFSkU2V0FGZXUyOFhy
        NzBHU2pQUDIzNmdSYzVPOU43L2pZL1EKLS0tIDUwQUpMVC8vV0U0VXhqazBzSU4v
        Tnlabmw2QzBiSEtTUFk1NmZFS0xtV3cKWJlYCosmkqbBnz3cQDttLPIFZFsiK9gu
        UNPmO8C4ytsBBr6WcLCBpeCM6FDe6sOXQIu92BBHuIvPvi7c6tFRzA==
        -----END AGE ENCRYPTED FILE-----
      recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
  encrypted_regex: ^(data|stringData)$
  lastmodified: "2026-07-29T16:15:56Z"
  mac: ENC[AES256_GCM,data:YABc46nvgjYBceLIEv8aiIz4CMSwRyOVC3gD7ZlKFSRYTIRqWSJh27FVLESLK3EezoNf/ameTKiVeJvt/5FI/lxz3JpNn7kNGhIZ2NPIEPAP5d0s6A1lgfEwSZneSnTDx+XRJWETd3noN0RPA6nqz1OxVxgDkVytD68hpoFQ/18=,iv:oGBkKwoRP8asIo/yBhaDHJk9or9tsxVliE8/uOoIivs=,tag:VlL5sChCtQI3T8Uu05Woyw==,type:str]
  mac_only_encrypted: true
  version: 3.13.3
