---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: cloudflare-tunnel-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret-apps
    namespace: doppler-operator-system
  project: home-dc-kubernetes
  config: apps
  managedSecret:
    name: cloudflare-tunnel-secret
    namespace: network
  secrets:
    - TUNNEL_TOKEN_APPS
  processors:
    TUNNEL_TOKEN_APPS:
      asName: TUNNEL_TOKEN
