apiVersion: v1
kind: Secret
metadata:
  name: csi-cephfs-secret
  namespace: kube-system
type: Opaque
stringData:
  adminID: admin
  adminKey: ENC[AES256_GCM,data:8Z9Z6gkR4lE6mUoIc/Q8wb4UZW9Xtnpf9tT5W0kP6DibORlBKKpGUQ==,iv:rSd1jVpQYHDMX1TFCuJKIQ+i9XBELg8nNcXlFz6k6ps=,tag:tpHLSW++h+YzrUipPanC7w==,type:str]
  userID: admin
  userKey: ENC[AES256_GCM,data:Ea4AFkI8vFvg+6Vhm6j8lVcimPcXdFQzo8c94EhkJhGRrFhquP6b+g==,iv:GZJq0adRJl+dnnJ+s4c1wZ0XV9pRBqlEW9uOP4dr4fU=,tag:kNcvisb6HsQGoIrmNIpclg==,type:str]
sops:
  age:
    - recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzOEJ1NUo5aEduMDBhZ1lh
        SytzS0ZFWTlvY1VjaEFROCtBM09Dcml5d2lFCmJQN253d2Q3ajJMRVA2THU1NlR0
        Zzg5ZG44dW45aWhsV1VnK1I2UjFURDgKLS0tIDFjemVtZUl2QzVtcm1CVGdXNG51
        VTF1aFFBTWZua3FRM1BsQlhWdWMrUUEKaZM+/aVc5fx12dYQ+LFmx6REIYfUBLGJ
        lotF8tjS+kdrOyQ+wLQTXGeBaizvGSnzhzm1w3lhZS0s592BA/9HLw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2026-04-28T20:37:15Z"
  mac: ENC[AES256_GCM,data:KTh9lw+eqc09nRtTezK2FdQCoJ0eDYE+zZWNkDq5qWL32JPfDaNeUTdTjSyM3o5keCHBToIy/GH4pp0TkpCvTlfoWju57mHxssVfo1tvpQWXdC2Nfi4yGGLIvtCNgYc9qRnSSOb5/5KjKi/cXethieAK8nf2cCUWPjdmx2Ovulg=,iv:9l+Y1ZDL5c12HbZyUjhCpMU0zL6DkZeeNTxeAF7vcfM=,tag:TETPMUIYe5YmIO5KKqUT9w==,type:str]
  encrypted_regex: ^(adminKey|userKey|.*Key)$
  mac_only_encrypted: true
  version: 3.12.2
