---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: terraform-controller
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/fabricesemti80/home-dc-kubernetes.git"
      path: kubernetes/apps/infrastructure/terraform-controller
      targetRevision: main
      ref: repo
    - repoURL: https://flux-iac.github.io/tofu-controller
      chart: tofu-controller
      targetRevision: 0.16.4
      helm:
        releaseName: tf-controller
        valueFiles:
          - $repo/kubernetes/apps/infrastructure/terraform-controller/values.yaml
  destination:
    name: infra-cluster
    namespace: infrastructure
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 5
      backoff:
        duration: 30s
    syncOptions:
      - CreateNamespace=true
