---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: planka-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: planka-secrets
    namespace: productivity
    type: Opaque
  secrets:
    - PLANKA_DATABASE_URL
    - PLANKA_SECRET_KEY
    - PLANKA_DB_PASSWORD
    - PLANKA_DEFAULT_ADMIN_EMAIL
    - PLANKA_DEFAULT_ADMIN_PASSWORD
