apiVersion: v1
kind: Secret
metadata:
    name: doppler-token-secret-infra
    namespace: doppler-operator-system
type: Opaque
stringData:
    serviceToken: ENC[AES256_GCM,data:jpfaosHFf9ZGD/t97i4E4bOTRvGDoxjGoMguX/ze2uLKwQi+k+xcA7YowTgKQFlgCbZvARGNZw==,iv:Z3JTCIDC45Kl11+9B4vLVC3GBEPxpIHjvmaJXPZa14I=,tag:gTVMa84YNE8kSy21QpPrng==,type:str]
sops:
    age:
        - enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBmUmlEcEREMkw4c1NCdk91
            MXUxNnNrSzFpTHNQUEQ4dHBwTUlsQkZZbEN3CnVyK2NPVDFSZkJGUTF6Z1hqVGd5
            ZEMxMzY5Z2ZpOWd4cTlzTXRoQmRBRmsKLS0tIDFwRlV4Vi92VEttbnBGcXB3SG4r
            S3lwa295cUIxQ1RQeW1kTm8rSUVYd0UKs1Eykqei8wUxFV1qT4sdCqDSwcUZGlj9
            OyekHnA44taMqfGsUCeKp1L3DV2RD2PxDYcCEyF0TjTp4ZCmJuCHCQ==
            -----END AGE ENCRYPTED FILE-----
          recipient: age1saea3t7l67lavg0ardepzys6egp50g82uvks98pk53xdlj57uf8sa2arcs
    encrypted_regex: ^(data|stringData)$
    lastmodified: "2026-07-29T16:16:42Z"
    mac: ENC[AES256_GCM,data:dLeoZh0nzuDXW8+/ToqL3LyTGFpqoGkv23fXSZ6E2r6YagiIx0tEntiwUhfMg/Y+c7dDrZeL4C7+lyGrNMtpWDrjZNsQy44mcenkKayI8frgtodLJjhGedxx2VEkuXFaBjR1+wUUlkN68+C3Ge3EcN7YyAL0xOAOu1GxTqyP7R8=,iv:BKYQ6/QKO742gj4b6zWBSdZHwFpGaOLbRBysZhrwqRw=,tag:akyZswIkQVA0/bzYZx4kGA==,type:str]
    mac_only_encrypted: true
    version: 3.13.3
