---
apiVersion: v1
kind: ConfigMap
metadata:
  name: pihole-dnsmasq
  namespace: network
data:
  99-krapulax-home.conf: |
    address=/kubernetes.krapulax.home/10.0.40.102
    address=/photos.krapulax.home/10.0.40.102
    address=/jellyfin.krapulax.home/10.0.40.102
    address=/qbittorrent.krapulax.home/10.0.40.102
    address=/prowlarr.krapulax.home/10.0.40.102
    address=/radarr.krapulax.home/10.0.40.102
    address=/requests.krapulax.home/10.0.40.102
    address=/sabnzbd.krapulax.home/10.0.40.102
    address=/sonarr.krapulax.home/10.0.40.102
    address=/tdarr.krapulax.home/10.0.40.102
    address=/ha.krapulax.home/10.0.40.102
    address=/minecraft.krapulax.home/10.0.40.112
    address=/dns.krapulax.home/10.0.40.106
    address=/kestra.krapulax.home/10.0.40.106
    address=/litellm.krapulax.home/10.0.40.106
    address=/pulse.krapulax.home/10.0.40.106
