#!/usr/bin/env python3
"""Generate AutoKuma static monitors from public Kubernetes HTTPRoutes."""

from __future__ import annotations

import argparse
import json
import re
import subprocess
import sys
import tempfile
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
KUBERNETES_DIR = ROOT / "kubernetes"
OUTPUT = (
    ROOT
    / "kubernetes/apps/infra-cluster/monitoring/uptime-kuma-infra/config/autokuma-monitors.yaml"
)
PUBLIC_HOST_RE = re.compile(r"^[a-z0-9][a-z0-9.-]*\.krapulax\.dev$")

DISPLAY_NAME_OVERRIDES = {
    "argo.krapulax.dev": "Argo CD",
    "alertmanager.krapulax.dev": "Alertmanager",
    "code.krapulax.dev": "Code Server",
    "convertx.krapulax.dev": "ConvertX",
    "echo.krapulax.dev": "Echo",
    "glance.krapulax.dev": "Glance",
    "grafana.krapulax.dev": "Grafana",
    "homepage.krapulax.dev": "Homepage",
    "jelly.krapulax.dev": "Jellyfin",
    "linkwarden.krapulax.dev": "Linkwarden",
    "n8n.krapulax.dev": "n8n",
    "nginx-test.krapulax.dev": "NGINX Test",
    "pdf.krapulax.dev": "Stirling PDF",
    "photos.krapulax.dev": "Immich",
    "prometheus.krapulax.dev": "Prometheus",
    "prowlarr.krapulax.dev": "Prowlarr",
    "pulse.krapulax.dev": "Pulse",
    "qbittorrent.krapulax.dev": "qBittorrent",
    "radarr.krapulax.dev": "Radarr",
    "requests.krapulax.dev": "Jellyseerr",
    "sabnzbd.krapulax.dev": "SABnzbd",
    "sonarr.krapulax.dev": "Sonarr",
    "tdarr.krapulax.dev": "Tdarr",
    "uptime.krapulax.dev": "Uptime Kuma",
}

YQ_QUERY = r'''
select(.kind == "HTTPRoute") |
(.metadata.annotations."gethomepage.dev/name" // .metadata.name // "monitor") as $name |
(.spec.hostnames // [])[] |
[$name, .] | @tsv
'''.strip()


def route_files() -> list[Path]:
    candidates = set(KUBERNETES_DIR.rglob("*.yaml")) | set(
        KUBERNETES_DIR.rglob("*.yml")
    )
    return sorted(
        path
        for path in candidates
        if "http-route" in path.name.lower() or "httproute" in path.name.lower()
    )


def discover_monitors() -> dict[str, str]:
    monitors: dict[str, str] = {}

    for path in route_files():
        result = subprocess.run(
            ["yq", "eval-all", "-r", YQ_QUERY, str(path)],
            cwd=ROOT,
            text=True,
            capture_output=True,
            check=False,
        )
        if result.returncode != 0:
            print(
                f"warning: skipping {path.relative_to(ROOT)}: {result.stderr.strip()}",
                file=sys.stderr,
            )
            continue

        for line in result.stdout.splitlines():
            if not line or "\t" not in line:
                continue
            discovered_name, hostname = line.split("\t", 1)
            hostname = hostname.strip().lower()
            if not PUBLIC_HOST_RE.fullmatch(hostname):
                continue

            name = DISPLAY_NAME_OVERRIDES.get(hostname, discovered_name.strip())
            previous = monitors.get(hostname)
            if previous is not None and previous != name:
                raise RuntimeError(
                    f"conflicting names for {hostname}: {previous!r} and {name!r}"
                )
            monitors[hostname] = name

    if not monitors:
        raise RuntimeError("no public *.krapulax.dev HTTPRoute hostnames were discovered")

    return dict(sorted(monitors.items()))


def monitor_key(hostname: str) -> str:
    return hostname.removesuffix(".krapulax.dev").replace(".", "-") + ".json"


def render(monitors: dict[str, str]) -> str:
    lines = [
        "---",
        "# Generated by scripts/generate-autokuma-monitors.py.",
        "# Updated automatically by .github/workflows/generate-autokuma-monitors.yaml.",
        "# Do not edit this file manually.",
        "apiVersion: v1",
        "kind: ConfigMap",
        "metadata:",
        "  name: autokuma-monitors",
        "  namespace: monitoring",
        "data:",
    ]

    for hostname, name in monitors.items():
        payload = {
            "type": "http",
            "name": name,
            "url": f"https://{hostname}",
            "interval": 60,
            "max_retries": 3,
        }
        lines.append(f"  {monitor_key(hostname)}: |-")
        lines.extend(
            f"    {line}" for line in json.dumps(payload, indent=2).splitlines()
        )

    return "\n".join(lines) + "\n"


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument(
        "--check",
        action="store_true",
        help="fail if the committed ConfigMap differs from generated output",
    )
    args = parser.parse_args()

    try:
        monitors = discover_monitors()
        generated = render(monitors)
    except (OSError, RuntimeError) as exc:
        print(f"error: {exc}", file=sys.stderr)
        return 1

    if args.check:
        existing = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if existing != generated:
            print(
                "AutoKuma monitor inventory is stale. GitHub Actions normally "
                "regenerates it; local fallback: task monitoring:generate-autokuma",
                file=sys.stderr,
            )
            return 1
        print("AutoKuma monitor inventory is up to date.")
        return 0

    OUTPUT.parent.mkdir(parents=True, exist_ok=True)
    with tempfile.NamedTemporaryFile(
        mode="w", encoding="utf-8", dir=OUTPUT.parent, delete=False
    ) as handle:
        handle.write(generated)
        temporary = Path(handle.name)
    temporary.replace(OUTPUT)
    print(f"Generated {len(monitors)} monitors in {OUTPUT.relative_to(ROOT)}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
