---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: paperclip-secrets
  namespace: doppler-operator-system
  annotations:
    argocd.argoproj.io/sync-wave: '-1'
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: paperclip-secrets
    namespace: ai
    type: Opaque
  secrets:
    - PAPERCLIP_BETTER_AUTH_SECRET
    - PAPERCLIP_MASTER_KEY
    - OPENAI_API_KEY
    - ANTHROPIC_API_KEY
