apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: mkdocs
  namespace: argo-system
spec:
  project: default
  sources:
    - repoURL: https://bjw-s.github.io/helm
      chart: app-template
      targetRevision: 5.0.1
      helm:
        releaseName: mkdocs
        valueFiles:
          - $values/kubernetes/apps/app-cluster/productivity/mkdocs/values.yaml
    - repoURL: https://github.com/fabricesemti80/home-dc-kubernetes.git
      targetRevision: HEAD
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: productivity
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
