---
global:
  createDefaultServiceAccount: false

defaultPodOptions:
  automountServiceAccountToken: false

controllers:
  tdarr:
    strategy: Recreate
    pod:
      hostname: tdarr
      nodeSelector:
        kubernetes.io/hostname: k8s-ctrl-01
    containers:
      app:
        image:
          repository: ghcr.io/haveagitgat/tdarr
          tag: latest
        env:
          TZ: Europe/London
          PUID: "0"
          PGID: "0"
          UMASK_SET: "002"
          serverIP: 0.0.0.0
          serverPort: "8266"
          webUIPort: "8265"
          internalNode: "false"
          inContainer: "true"
          ffmpegVersion: "7"
          auth: "false"
          openBrowser: "false"
          maxLogSizeMB: "10"
          cronPluginUpdate: ""
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              tcpSocket:
                port: 8265
              initialDelaySeconds: 60
              periodSeconds: 20
              timeoutSeconds: 5
              failureThreshold: 6
          readiness: *probes
        resources:
          requests:
            cpu: 250m
            memory: 1Gi
          limits:
            cpu: 500m
            memory: 4Gi

  worker-k8s-ctrl-01:
    strategy: Recreate
    pod:
      nodeSelector:
        kubernetes.io/hostname: k8s-ctrl-01
    containers:
      app: &worker
        image:
          repository: ghcr.io/haveagitgat/tdarr_node
          tag: latest
        env:
          TZ: Europe/London
          PUID: "0"
          PGID: "0"
          UMASK_SET: "002"
          nodeName: tdarr-k8s-ctrl-01
          serverURL: http://tdarr:8266
          inContainer: "true"
          ffmpegVersion: "7"
          nodeType: mapped
          priority: "-1"
          cronPluginUpdate: ""
          maxLogSizeMB: "10"
          pollInterval: "2000"
          startPaused: "false"
          transcodecpuWorkers: "3"
          healthcheckcpuWorkers: "1"
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: 3500m
            memory: 4Gi

  worker-k8s-ctrl-02:
    strategy: Recreate
    pod:
      nodeSelector:
        kubernetes.io/hostname: k8s-ctrl-02
    containers:
      app:
        <<: *worker
        env:
          TZ: Europe/London
          PUID: "0"
          PGID: "0"
          UMASK_SET: "002"
          nodeName: tdarr-k8s-ctrl-02
          serverURL: http://tdarr:8266
          inContainer: "true"
          ffmpegVersion: "7"
          nodeType: mapped
          priority: "-1"
          cronPluginUpdate: ""
          maxLogSizeMB: "10"
          pollInterval: "2000"
          startPaused: "false"
          transcodecpuWorkers: "4"
          healthcheckcpuWorkers: "1"
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "4"
            memory: 4Gi

  worker-k8s-ctrl-03:
    strategy: Recreate
    pod:
      nodeSelector:
        kubernetes.io/hostname: k8s-ctrl-03
    containers:
      app:
        <<: *worker
        env:
          TZ: Europe/London
          PUID: "0"
          PGID: "0"
          UMASK_SET: "002"
          nodeName: tdarr-k8s-ctrl-03
          serverURL: http://tdarr:8266
          inContainer: "true"
          ffmpegVersion: "7"
          nodeType: mapped
          priority: "-1"
          cronPluginUpdate: ""
          maxLogSizeMB: "10"
          pollInterval: "2000"
          startPaused: "false"
          transcodecpuWorkers: "4"
          healthcheckcpuWorkers: "1"
        resources:
          requests:
            cpu: "1"
            memory: 1Gi
          limits:
            cpu: "4"
            memory: 4Gi

service:
  app:
    controller: tdarr
    ports:
      http:
        port: 8265
        targetPort: 8265
      server:
        port: 8266
        targetPort: 8266

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: cephfs
    size: 5Gi
    advancedMounts:
      tdarr:
        app:
          - path: /app/server
            subPath: server
          - path: /app/configs
            subPath: configs
          - path: /app/logs
            subPath: logs
      worker-k8s-ctrl-01:
        app:
          - path: /app/configs
            subPath: configs/worker-k8s-ctrl-01
          - path: /app/logs
            subPath: logs/worker-k8s-ctrl-01
      worker-k8s-ctrl-02:
        app:
          - path: /app/configs
            subPath: configs/worker-k8s-ctrl-02
          - path: /app/logs
            subPath: logs/worker-k8s-ctrl-02
      worker-k8s-ctrl-03:
        app:
          - path: /app/configs
            subPath: configs/worker-k8s-ctrl-03
          - path: /app/logs
            subPath: logs/worker-k8s-ctrl-03
  media:
    enabled: true
    existingClaim: media-library-pvc
    advancedMounts:
      tdarr:
        app:
          - path: /media
      worker-k8s-ctrl-01:
        app:
          - path: /media
      worker-k8s-ctrl-02:
        app:
          - path: /media
      worker-k8s-ctrl-03:
        app:
          - path: /media
  transcode-cache:
    enabled: true
    existingClaim: media-library-pvc
    advancedMounts:
      tdarr:
        app:
          - path: /temp
            subPath: tdarr-cache
      worker-k8s-ctrl-01:
        app:
          - path: /temp
            subPath: tdarr-cache
      worker-k8s-ctrl-02:
        app:
          - path: /temp
            subPath: tdarr-cache
      worker-k8s-ctrl-03:
        app:
          - path: /temp
            subPath: tdarr-cache
