---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: uptime-kuma-credentials
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: uptime-kuma-credentials
    namespace: monitoring
    type: Opaque
  secrets:
    - UPTIME_KUMA_USERNAME
    - UPTIME_KUMA_PASSWORD
