apiVersion: externaldns.k8s.io/v1alpha1
kind: DNSEndpoint
metadata:
  name: cloudflare-tunnel
spec:
  endpoints:
    - dnsName: external.krapulax.dev
      recordType: CNAME
      targets:
        - c153a412-005f-4c07-8b89-34ec5628005a.cfargotunnel.com
    - dnsName: external-infra.krapulax.dev
      recordType: CNAME
      targets:
        - 406a2618-549e-432b-8e52-473938713a8c.cfargotunnel.com
    - dnsName: nginx-test.krapulax.dev
      recordType: CNAME
      targets:
        - external.krapulax.dev
    - dnsName: pulse.krapulax.dev
      recordType: CNAME
      targets:
        - external-infra.krapulax.dev
    - dnsName: kestra.krapulax.dev
      recordType: CNAME
      targets:
        - external-infra.krapulax.dev
    - dnsName: uptime.krapulax.dev
      recordType: CNAME
      targets:
        - external-infra.krapulax.dev
    - dnsName: grafana.krapulax.dev
      recordType: CNAME
      targets:
        - external.krapulax.dev
