---
fullnameOverride: kestra-postgres
useDeployment: true
nodeSelector:
  kubernetes.io/hostname: infra-cp-01
tolerations:
  - key: node-role.kubernetes.io/control-plane
    operator: Exists
    effect: NoSchedule
affinity: {}
settings:
  existingSecret: kestra-postgres
userDatabase:
  existingSecret: kestra-postgres
storage:
  className: local-path
  requestedSize: 10Gi
  accessModes:
    - ReadWriteOnce
  keepPvc: true
