---
global:
  createDefaultServiceAccount: false

controllers:
  copyparty:
    replicas: 1
    strategy: Recreate
    containers:
      app:
        image:
          repository: docker.io/copyparty/ac
          tag: "1.20.21"
        args:
          - -p
          - "3923"
          - -a
          - media:$(COPYPARTY_MEDIA_PASSWORD)
          - -v
          - /media::rwmd,media
          - --hist
          - /config/hists
          - --no-robots
          - --xff-hdr
          - cf-connecting-ip
          - --acao
          - https://files.krapulax.dev
        env:
          TZ: Europe/London
          COPYPARTY_MEDIA_PASSWORD:
            valueFrom:
              secretKeyRef:
                name: copyparty-secrets
                key: COPYPARTY_MEDIA_PASSWORD
        probes:
          liveness: &probes
            enabled: true
            custom: true
            spec:
              httpGet:
                path: /
                port: &port 3923
              initialDelaySeconds: 10
              periodSeconds: 15
              timeoutSeconds: 5
              failureThreshold: 6
          readiness: *probes
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: false
          capabilities: {drop: ["ALL"]}
        resources:
          requests:
            cpu: 50m
            memory: 128Mi
          limits:
            cpu: 500m
            memory: 512Mi

defaultPodOptions:
  automountServiceAccountToken: false
  annotations:
    reloader.stakater.com/auto: "true"
  securityContext:
    runAsNonRoot: false
    runAsUser: 0
    runAsGroup: 0

service:
  app:
    controller: copyparty
    ports:
      http:
        port: *port

persistence:
  config:
    type: persistentVolumeClaim
    accessMode: ReadWriteMany
    storageClass: cephfs
    size: 2Gi
    globalMounts:
      - path: /config
  media:
    enabled: true
    existingClaim: media-library-pvc
    globalMounts:
      - path: /media
