---
apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ./namespace.yaml
  - ./http-route-internal.yaml
  - ./http-route.yaml
  - ./doppler-secret.yaml
configMapGenerator:
  - name: pulse-system-config
    namespace: monitoring
    files:
      - system.json
generatorOptions:
  disableNameSuffixHash: true
