---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: affine-secrets
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret-apps
    namespace: doppler-operator-system
  project: home-dc-kubernetes
  config: apps
  managedSecret:
    name: affine-secrets
    namespace: productivity
    type: Opaque
  secrets:
    - AFFINE_DB_PASSWORD
    - DATABASE_URL
