---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kestra-basic-auth
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: kestra-basic-auth
    namespace: kestra
    type: Opaque
  secrets:
    - KESTRA_BASIC_AUTH_USERNAME
    - KESTRA_BASIC_AUTH_PASSWORD
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kestra-postgres
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: kestra-postgres
    namespace: kestra
    type: Opaque
  secrets:
    - POSTGRES_USER
    - POSTGRES_PASSWORD
    - POSTGRES_DB
    - USERDB_USER
    - USERDB_PASSWORD
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: versitygw-root
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: versitygw-root
    namespace: kestra
    type: Opaque
  secrets:
    - ROOT_ACCESS_KEY
    - ROOT_SECRET_KEY
---
apiVersion: secrets.doppler.com/v1alpha1
kind: DopplerSecret
metadata:
  name: kestra-homelab-ops
  namespace: doppler-operator-system
spec:
  tokenSecret:
    name: doppler-token-secret
    namespace: doppler-operator-system
  project: project-homelab
  config: dev_homelab
  managedSecret:
    name: kestra-homelab-ops
    namespace: kestra
    type: Opaque
  processors:
    HOMELAB_SSH_PRIVATE_KEY:
      asName: SECRET_HOMELAB_SSH_PRIVATE_KEY
    HOMELAB_SSH_KNOWN_HOSTS:
      asName: SECRET_HOMELAB_SSH_KNOWN_HOSTS
  secrets:
    - HOMELAB_SSH_PRIVATE_KEY
    - HOMELAB_SSH_KNOWN_HOSTS
