---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: termix
  namespace: argo-system
  annotations:
    argocd.argoproj.io/sync-wave: '0'
spec:
  project: kubernetes
  sources:
    - repoURL: "https://github.com/fabricesemti80/home-dc-kubernetes.git"
      path: kubernetes/apps/productivity/termix
      targetRevision: main
      ref: repo
    - repoURL: ghcr.io/bjw-s-labs/helm
      chart: app-template
      targetRevision: 5.0.1
      helm:
        releaseName: termix
        valueFiles:
          - $repo/kubernetes/apps/productivity/termix/values.yaml
  destination:
    name: in-cluster
    namespace: productivity
  syncPolicy:
    automated:
      allowEmpty: true
      prune: true
      selfHeal: true
    retry:
      limit: 1
      backoff:
        duration: 10s
        factor: 2
        maxDuration: 3m
    syncOptions:
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=true
      - ServerSideApply=true
      - PruneLast=true
      - RespectIgnoreDifferences=true
